export default Object.freeze({
  LISTING_DETAILS: 'ListingDetails',
  LISTING_EDIT: 'ListingEdit',
  LISTING: 'Listing',
  LOGIN: 'Login',
  MESSAGES: 'Messages',
  REGISTER: 'Register',
  FORGOTPASSWORD: 'ForgotPassword',
  MY_LISTINGS: 'MyListings',
  WELCOME: 'Welcome',
  PROFILE: 'Profile',
  EMAIL: 'ChangeEmail',
  PASSWORD: 'ChangePassword',
  NAME: 'ChangeName',
  CONFIRM: 'Confirm',
  ROOT: 'Root',
  ACCOUNT: 'Account',
});
